POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhd25lZCIsImlkIjoiNjFiZjY4MmI3NzYzZWU2Y2EyNjhkY2YyIiwiaWF0IjoxNjQwMzY1ODA0fQ._MoCm43W3xmU-1NW0qr0IM9M69ILl0_OpfnJX90tTbw

{
    "title": "fiFTH blog",
    "author": "ifan",
    "url": "/api/yolo",
    "likes": 3
}